## Operaciones Básicas

In [414]:
p1=500
print(p1)
p1

500


500

In [415]:
p2=200.5
p2

200.5

In [417]:
print(type(p1))
print(type(p2))

<class 'int'>
<class 'float'>


In [420]:
w=int(p2)

In [421]:
type(w)

int

In [422]:
a = 5
a = a + 1 
a

6

In [423]:
a+=1
a

7

In [427]:
p=5
q=200
total=p*q
total

5

In [428]:
total/p

1.0

## Print

In [429]:
x = "Curso de Backtesting y Strees Testing"
print(x)
print(type(x))
len(x)

Curso de Backtesting y Strees Testing
<class 'str'>


37

In [430]:
print("Me interesa el {} en este ciclo".format(x))

Me interesa el Curso de Backtesting y Strees Testing en este ciclo


In [431]:
y="2020-II"

In [432]:
print("Me interesa el {} en este ciclo {}".format(x, y))

Me interesa el Curso de Backtesting y Strees Testing en este ciclo 2020-II


## Input

In [433]:
nombre = input("Bienvenido al curso, Cuál es tu nombre?: ")
print('Hola', nombre)

Bienvenido al curso, Cuál es tu nombre?: Johnny
Hola Johnny


In [434]:
nombre = input("Bienvenido al curso, ingresa tu nombre: ")
edad = input("Ingresa tu edad: ")
print("Mi nombre es {}, tengo {} años".format(nombre,edad))

Bienvenido al curso, ingresa tu nombre: Johnny
Ingresa tu edad: 36
Mi nombre es Johnny, tengo 36 años


In [436]:
p = input("Ingresa el precio: ")
p=int(p)
q = input("Ingresa la cantidad: ")
q=int(q)
print('El total de la cuenta es: {}'.format(p*q)) 

Ingresa el precio: 100
Ingresa la cantidad: 9
El total de la cuenta es: 900


## Tipos de Datos

### Booleanos

In [438]:
e=True
e

True

In [442]:
p=100
q=200
p<q  #podemos probar con < y >

True

### Listas (List)

In [443]:
lista = [1, 2, 3]
lista

[1, 2, 3]

In [444]:
type(lista)

list

In [445]:
lista = [2, "google", 5]
lista

[2, 'google', 5]

In [446]:
lista = ["google", [3, 6, 7]]
lista

['google', [3, 6, 7]]

In [447]:
lista = [2, "google", 5]
lista[2] #pueden jugar con las posiciones, solo recordar que la posición inicial arranca en 0

5

In [448]:
lista = ["google", [3, 6, 7], ["amazon", 5, 6]]
lista[2][0] #referencia la posición dentro de una lista y luego la que esta dentro del elemento lista

'amazon'

In [451]:
type(lista) #ver los tipos

list

In [453]:
lista[-1][2] #negativos arranca desde la última posición

6

In [454]:
lista = [2, 5, 7, "GOOG", "SP500", "AMZN", 15]
lista[3:5]

['GOOG', 'SP500']

In [455]:
lista[3:]

['GOOG', 'SP500', 'AMZN', 15]

In [456]:
len(lista)

7

### Diccionarios (Dictionary)

In [457]:
dic = {'key1':'value1',
       'key2':'value2', 
       'key3':'value3'}

In [458]:
type(dic)

dict

In [459]:
dic["key1"]

'value1'

In [460]:
type(dic["key1"])

str

In [461]:
dic2 =  {"key1": 1500,
         "key2": 1000,
         "key3": 2000}
dic2

{'key1': 1500, 'key2': 1000, 'key3': 2000}

In [462]:
dic2["key3"]

2000

In [463]:
dic2["key4"]=1800
dic2

{'key1': 1500, 'key2': 1000, 'key3': 2000, 'key4': 1800}

In [464]:
del dic2["key4"]
dic2

{'key1': 1500, 'key2': 1000, 'key3': 2000}

In [466]:
del dic2 #borramos esta variable
dic2

NameError: name 'dic2' is not defined

### Cadenas (String)

In [467]:
nombre = "Johnny" 
apellido = "Pantoja"
nombre_completo = nombre +" "+ apellido
nombre_completo

'Johnny Pantoja'

In [469]:
nombre_completo.lower() #probar con lower

'johnny pantoja'

In [470]:
v=nombre_completo.split() #probar asignándolo a una variable
v

['Johnny', 'Pantoja']

In [471]:
type(v)

list

In [472]:
v[1]

'Pantoja'

In [475]:
c = 'johnny.pantoja@gmail.com'
z = c.split('@')
z

['johnny.pantoja', 'gmail.com']

### Tuplas (Tuple)

In [477]:
tuple_1 = ('google', 'amazon', 10, 15, 1992);
tuple_2 = (450, 55, 977, 2100);

In [478]:
tuple_1[-1] #probar las opciones

1992

In [479]:
tuple_1[1:3] #probar con diferentes opciones de filetear la tupla

('amazon', 10)

In [480]:
tuple_1[1]='facebook'

TypeError: 'tuple' object does not support item assignment

In [481]:
tuple_3=tuple_1+tuple_2
tuple_3

('google', 'amazon', 10, 15, 1992, 450, 55, 977, 2100)

### Collecciones (Sets)

In [483]:
set_1 = {'GOOG', 'APPL', 'T','TSLA','T','APPL'}
set_1
type(set_1)

set

In [484]:
lista = ['GOOG', 'APPL', 'T','TSLA','T','APPL', 5, 6, 5]
lista2 = list(set(lista))
lista2

['GOOG', 5, 6, 'T', 'APPL', 'TSLA']

In [485]:
type(lista2)

list

### Operadores de Comparación

In [486]:
s1 = 1000
s2 = 1000
s1 == s2 #probar con < , > , <= , >= , !=

True

### Operadores Lógicos

In [487]:
True or False  #probar diferentes combinaciones con and y or

True

In [488]:
(10>3) and (9==3)

False

In [489]:
(9>3) or (12==10)

True

### Sentencias Condicionales

In [490]:
if 10 > 9:  #probemos con diferentes operadores
    print('Verdadero')
else:
    print('Falso')

Verdadero


In [ ]:
if 5 > 7:
    print('Verdadero')
elif 2 > 4:
    print('Falso')
else:
    print('Ninguno')

In [493]:
nombre = input('Ingresa tu nombre:')
if nombre.lower() == 'johnny':  #probar con variantes upper() , lower()
    print("Acceso Otorgado")
else:
    print("Acceso denegado")

Ingresa tu nombre:JOHnny
Acceso Otorgado


In [494]:
nombre = input('Ingresa tu nombre/apellido:')
if nombre == 'Johnny' or nombre =='Pantoja':
    print("Acceso Otorgado")
else:
    print("Acceso Denegado")

Ingresa tu nombre/apellido:Pantoja
Acceso Otorgado


## BUCLES

### FOR

In [495]:
lista = [1, 2, 3, 4, 5]

In [496]:
for i in lista:
    print(i)

1
2
3
4
5


In [497]:
for i in lista:
    print(i)
    print('Hola')

1
Hola
2
Hola
3
Hola
4
Hola
5
Hola


### RANGE

In [498]:
for i in range(5):
    print(i)

0
1
2
3
4


In [499]:
for i in reversed(range(5)):
    print(i)

4
3
2
1
0


In [500]:
for i in range(1, 20, 3): #probar también con decrecimientos
    print(i)

1
4
7
10
13
16
19


### WHILE

In [501]:
i = 0
while i <=8:
    print(i)
    i = i + 1

0
1
2
3
4
5
6
7
8


### BREAK / CONTINUE

In [502]:
lista

[1, 2, 3, 4, 5]

In [503]:
for i in lista:
    print(i)
    if i == 3:
        break

1
2
3


In [504]:
for i in lista:
    if i%2 == 0:
        continue
    print(i)

1
3
5


### BUCLES ANIDADOS

In [505]:
for x in range(1,3): 
    for y in range(1, 4): 
        print('{} * {} = {}'.format(x, y, x*y))

1 * 1 = 1
1 * 2 = 2
1 * 3 = 3
2 * 1 = 2
2 * 2 = 4
2 * 3 = 6


In [506]:
color = ['black', 'white', 'gold']
equipo = ['iphone', 'samsung', 'blackberry']
for i in color:
    for j in equipo:
        print(i, j)

black iphone
black samsung
black blackberry
white iphone
white samsung
white blackberry
gold iphone
gold samsung
gold blackberry


### LISTAS BASADAS EN LISTAS

In [507]:
input_list = [1, 2, 3, 4]
output_list = []
for element in input_list:
    output_list.append(element**2)
output_list

[1, 4, 9, 16]

In [508]:
output_list=[i ** 2  for i in input_list]
output_list

[1, 4, 9, 16]

In [509]:
input_list = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
output_list = []
for i in input_list:
    if i % 2==0:
        output_list.append(i**2)
output_list

[4, 16, 36, 64, 100]

In [510]:
output_list = [i**2  for i in input_list if i%2 == 0]
output_list

[4, 16, 36, 64, 100]

### FUNCIONES

In [511]:
def func1():
    print('Hola')

In [512]:
func1()

Hola


In [513]:
def squared(x):
    return x ** 2

In [514]:
squared(5)

25

In [515]:
def func2(x):
    print("Mi portafolio es de {} soles".format(x))

In [516]:
func2(2000)

Mi portafolio es de 2000 soles


### EXPRESIONES LAMBDA

In [517]:
y = lambda x:x**2

In [518]:
y(3)

9

In [519]:
def suma(x, y, z):
    return x+y+z

In [520]:
suma(3,5,7)

15

In [521]:
suma2 = lambda x, y, z : x+y+z  

In [522]:
suma2(3,5,7)

15

### FILTROS

In [523]:
precios = [105, 5055, 40, 356, 923, 1443, 222, 62]

In [524]:
out = list(filter(lambda x: (x % 2 == 0),precios))
out

[40, 356, 222, 62]

In [525]:
out = list(filter(lambda x: (x>=100),precios))
out

[105, 5055, 356, 923, 1443, 222]

In [526]:
out = list(filter(lambda x: (x>=200 and x<=250),precios) )
out

[222]

# NUMPY
### Es una librería de álgebra lineal usada para array multidemensionales

In [527]:
import numpy as np 
my_list = [10, 20, 50, 60, 70]
my_list

[10, 20, 50, 60, 70]

In [528]:
x = np.array(my_list)
x

array([10, 20, 50, 60, 70])

In [529]:
type(x)

numpy.ndarray

In [530]:
matrix = np.array([[5, 8], [9, 13]])
matrix

array([[ 5,  8],
       [ 9, 13]])

In [531]:
type(matrix)

numpy.ndarray

### Funciones y Métodos

In [532]:
x = np.random.rand(10) #distribución uniforme
x

array([0.90238847, 0.91233758, 0.15813935, 0.94734273, 0.16498813,
       0.0934115 , 0.06354079, 0.68624084, 0.59826791, 0.99484388])

In [533]:
x = np.random.rand(5, 5)
x

array([[0.69396076, 0.40707943, 0.13288828, 0.00750644, 0.17664675],
       [0.57289483, 0.32508119, 0.36569854, 0.64220136, 0.01694374],
       [0.32874375, 0.16076966, 0.7485588 , 0.92438882, 0.36806156],
       [0.43027826, 0.4808542 , 0.61673268, 0.80397471, 0.67609195],
       [0.42576702, 0.15206746, 0.76866239, 0.4706616 , 0.09860138]])

In [534]:
x = np.random.randn(10) #distribución normal
x

array([ 0.63227532,  1.25449068, -1.74550569,  0.14550234, -1.21099527,
        0.48445389,  0.18643515,  0.41339027,  0.72719475,  0.08058504])

In [538]:
x = np.random.randint(1, 10)
x

8

In [539]:
x = np.random.randint(1, 100, 15)
x

array([83, 57, 88, 12, 36, 22, 56, 76,  1, 35, 20, 51, 51, 30, 98])

In [540]:
x = np.arange(1, 50)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [541]:
x = np.arange(1, 50, 5)
x

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46])

In [542]:
x = np.eye(5)
x

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [543]:
x = np.ones(5)
x

array([1., 1., 1., 1., 1.])

In [544]:
x = np.ones((5,5))
x

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [545]:
x = np.zeros(10)
x

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

### SHAPE, LENGTH, TYPE, RESHAPE, MAX/MIN

In [546]:
lista = [-30, 4, 50, 60, 29, 15, 22, 90]
x = np.array(lista)
x

array([-30,   4,  50,  60,  29,  15,  22,  90])

In [547]:
len(x)

8

In [548]:
x.shape

(8,)

In [550]:
matrix

array([[ 5,  8],
       [ 9, 13]])

In [549]:
matrix.dtype

dtype('int32')

In [551]:
matrix.shape

(2, 2)

In [552]:
x

array([-30,   4,  50,  60,  29,  15,  22,  90])

In [553]:
z = x.reshape(2,4)
print(x)
print(z)

[-30   4  50  60  29  15  22  90]
[[-30   4  50  60]
 [ 29  15  22  90]]


In [554]:
x.max()

90

In [555]:
x.min()

-30

In [556]:
x.argmax()

7

In [557]:
x.argmin()

0

### Operaciones Matemáticas

In [558]:
x = np.arange(1, 10)
x

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [559]:
y = np.arange(1, 10)
y

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [560]:
np.sqrt(4)

2.0

In [561]:
x**2

array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

In [562]:
np.sqrt(x**2)

array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [563]:
z = np.exp(y)
z

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03])

### Particiones e Indices

In [564]:
x = np.array([20, 40, 50, 21, 15])
x

array([20, 40, 50, 21, 15])

In [565]:
x[0:3]

array([20, 40, 50])

In [566]:
x[0:2] = 10
x

array([10, 10, 50, 21, 15])

In [567]:
matrix = np.random.randint(1,10, (5, 5))
matrix

array([[2, 1, 7, 3, 6],
       [4, 2, 4, 4, 7],
       [7, 2, 9, 6, 6],
       [8, 6, 4, 8, 2],
       [4, 3, 2, 2, 1]])

In [568]:
matrix[2]

array([7, 2, 9, 6, 6])

In [569]:
matrix[0][2]

7

In [570]:
mini_matrix = matrix[:3]
mini_matrix

array([[2, 1, 7, 3, 6],
       [4, 2, 4, 4, 7],
       [7, 2, 9, 6, 6]])

In [571]:
mini_matrix = matrix[2:]
mini_matrix

array([[7, 2, 9, 6, 6],
       [8, 6, 4, 8, 2],
       [4, 3, 2, 2, 1]])

In [573]:
mini_matrix = matrix[:, :2]
mini_matrix

array([[2, 1],
       [4, 2],
       [7, 2],
       [8, 6],
       [4, 3]])

In [574]:
mini_matrix = matrix[:, 2:]
mini_matrix

array([[7, 3, 6],
       [4, 4, 7],
       [9, 6, 6],
       [4, 8, 2],
       [2, 2, 1]])

### Selección de elementos (condicionales)

In [575]:
matrix = np.random.randint(1,10, (5, 5))
matrix

array([[3, 8, 8, 1, 2],
       [2, 1, 9, 8, 8],
       [5, 5, 4, 8, 6],
       [2, 3, 8, 7, 6],
       [4, 8, 8, 7, 2]])

In [576]:
new_matrix = matrix[matrix>3]
new_matrix

array([8, 8, 9, 8, 8, 5, 5, 4, 8, 6, 8, 7, 6, 4, 8, 8, 7])

In [578]:
new_matrix = matrix[matrix%2==0]
new_matrix

array([8, 8, 2, 2, 8, 8, 4, 8, 6, 2, 8, 6, 4, 8, 8, 2])

# PANDAS
### Pandas en una herramienta de manipulación, que usa una estrutctura de datos conocida como DataFrame

In [ ]:
import pandas as pd

In [579]:
my_list = ['AAPL','AMZN','T']
my_list

['AAPL', 'AMZN', 'T']

In [580]:
label   = ['stock#1', 'stock#2', 'stock#3']
label

['stock#1', 'stock#2', 'stock#3']

In [581]:
type(my_list)

list

In [582]:
type(label)

list

In [583]:
x_series = pd.Series(data = my_list, index = label)
x_series

stock#1    AAPL
stock#2    AMZN
stock#3       T
dtype: object

In [584]:
x_series.shape

(3,)

In [585]:
type(x_series)

pandas.core.series.Series

In [586]:
bank_client_df = pd.DataFrame({'Bank client ID':[111, 222, 333, 444], 
                               'Bank Client Name':['Chanel', 'Steve', 'Mitch', 'Ryan'], 
                               'Net worth [$]':[3500, 29000, 10000, 2000], 
                               'Years with bank':[3, 4, 9, 5]})
bank_client_df

Bank client ID Bank Client Name  Net worth [$]  Years with bank
0             111           Chanel           3500                3
1             222            Steve          29000                4
2             333            Mitch          10000                9
3             444             Ryan           2000                5

In [587]:
type(bank_client_df)

pandas.core.frame.DataFrame

In [589]:
bank_client_df.head(2) #se puede jugar con los argumentos y cambian las filas observadas

Bank client ID Bank Client Name  Net worth [$]  Years with bank
0             111           Chanel           3500                3
1             222            Steve          29000                4

In [591]:
bank_client_df.tail(2)  #se puede jugar con los argumentos y cambian las filas observadas

Bank client ID Bank Client Name  Net worth [$]  Years with bank
2             333            Mitch          10000                9
3             444             Ryan           2000                5

In [592]:
df_loyal = bank_client_df[(bank_client_df['Years with bank'] >= 5) ]
df_loyal

Bank client ID Bank Client Name  Net worth [$]  Years with bank
2             333            Mitch          10000                9
3             444             Ryan           2000                5

In [593]:
del bank_client_df['Bank client ID']
bank_client_df

Bank Client Name  Net worth [$]  Years with bank
0           Chanel           3500                3
1            Steve          29000                4
2            Mitch          10000                9
3             Ryan           2000                5

In [594]:
def valor(x):
    return x * 1.1

In [595]:
bank_client_df['Net worth [$]'].apply(valor)

0     3850.0
1    31900.0
2    11000.0
3     2200.0
Name: Net worth [$], dtype: float64

In [596]:
bank_client_df

Bank Client Name  Net worth [$]  Years with bank
0           Chanel           3500                3
1            Steve          29000                4
2            Mitch          10000                9
3             Ryan           2000                5

In [597]:
bank_client_df['Net worth [$]']=bank_client_df['Net worth [$]'].apply(valor)
bank_client_df

Bank Client Name  Net worth [$]  Years with bank
0           Chanel         3850.0                3
1            Steve        31900.0                4
2            Mitch        11000.0                9
3             Ryan         2200.0                5

In [598]:
bank_client_df['Bank Client Name'].apply(len)

0    6
1    5
2    5
3    4
Name: Bank Client Name, dtype: int64

In [599]:
bank_client_df['Years with bank'].sum()

21

In [600]:
bank_client_df.sort_values(by = 'Years with bank') 

Bank Client Name  Net worth [$]  Years with bank
0           Chanel         3850.0                3
1            Steve        31900.0                4
3             Ryan         2200.0                5
2            Mitch        11000.0                9

In [601]:
bank_client_df

Bank Client Name  Net worth [$]  Years with bank
0           Chanel         3850.0                3
1            Steve        31900.0                4
2            Mitch        11000.0                9
3             Ryan         2200.0                5

In [602]:
bank_client_df.sort_values(by = 'Years with bank', inplace = True)

In [603]:
bank_client_df

Bank Client Name  Net worth [$]  Years with bank
0           Chanel         3850.0                3
1            Steve        31900.0                4
3             Ryan         2200.0                5
2            Mitch        11000.0                9

In [604]:
df1 = pd.DataFrame({'A': ['A0', 'A1', 'A2', 'A3'],
                    'B': ['B0', 'B1', 'B2', 'B3'],
                    'C': ['C0', 'C1', 'C2', 'C3'],
                    'D': ['D0', 'D1', 'D2', 'D3']},index=[0, 1, 2, 3])
df1

A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3

In [605]:
df2 = pd.DataFrame({'A': ['A4', 'A5', 'A6', 'A7'],
                    'B': ['B4', 'B5', 'B6', 'B7'],
                    'C': ['C4', 'C5', 'C6', 'C7'],
                    'D': ['D4', 'D5', 'D6', 'D7']},index=[4, 5, 6, 7])
df2

A   B   C   D
4  A4  B4  C4  D4
5  A5  B5  C5  D5
6  A6  B6  C6  D6
7  A7  B7  C7  D7

In [606]:
df3 = pd.DataFrame({'A': ['A8', 'A9', 'A10', 'A11'],
                    'B': ['B8', 'B9', 'B10', 'B11'],
                    'C': ['C8', 'C9', 'C10', 'C11'],
                    'D': ['D8', 'D9', 'D10', 'D11']},index=[8, 9, 10, 11])
df3

A    B    C    D
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

In [607]:
pd.concat([df1, df2, df3])

A    B    C    D
0    A0   B0   C0   D0
1    A1   B1   C1   D1
2    A2   B2   C2   D2
3    A3   B3   C3   D3
4    A4   B4   C4   D4
5    A5   B5   C5   D5
6    A6   B6   C6   D6
7    A7   B7   C7   D7
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

In [608]:
raw_data = {'Bank Client ID': ['1', '2', '3', '4', '5'],
            'First Name': ['Nancy', 'Alex', 'Shep', 'Max', 'Allen'], 
            'Last Name': ['Rob', 'Ali', 'George', 'Mitch', 'Steve']}
Bank_df_1 = pd.DataFrame(raw_data, columns = ['Bank Client ID', 'First Name'])
Bank_df_1

Bank Client ID First Name
0              1      Nancy
1              2       Alex
2              3       Shep
3              4        Max
4              5      Allen

In [609]:
raw_data = {
        'Bank Client ID': ['6', '7', '8', '9', '10'],
        'First Name': ['Bill', 'Dina', 'Sarah', 'Heather', 'Holly'], 
        'Last Name': ['Christian', 'Mo', 'Steve', 'Bob', 'Michelle']}
Bank_df_2 = pd.DataFrame(raw_data, columns = ['Bank Client ID', 'First Name'])
Bank_df_2

Bank Client ID First Name
0              6       Bill
1              7       Dina
2              8      Sarah
3              9    Heather
4             10      Holly

In [610]:
raw_data = {
        'Bank Client ID': ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10'],
        'Annual Salary [$/year]': [25000, 35000, 45000, 48000, 49000, 32000, 33000, 34000, 23000, 22000]}
bank_df_salary = pd.DataFrame(raw_data, columns = ['Bank Client ID','Annual Salary [$/year]'])
bank_df_salary

Bank Client ID  Annual Salary [$/year]
0              1                   25000
1              2                   35000
2              3                   45000
3              4                   48000
4              5                   49000
5              6                   32000
6              7                   33000
7              8                   34000
8              9                   23000
9             10                   22000

In [611]:
bank_df_all = pd.concat([Bank_df_1, Bank_df_2])
bank_df_all

Bank Client ID First Name
0              1      Nancy
1              2       Alex
2              3       Shep
3              4        Max
4              5      Allen
0              6       Bill
1              7       Dina
2              8      Sarah
3              9    Heather
4             10      Holly

In [612]:
bank_df_all = pd.merge(bank_df_all, bank_df_salary, on = 'Bank Client ID')
bank_df_all

Bank Client ID First Name  Annual Salary [$/year]
0              1      Nancy                   25000
1              2       Alex                   35000
2              3       Shep                   45000
3              4        Max                   48000
4              5      Allen                   49000
5              6       Bill                   32000
6              7       Dina                   33000
7              8      Sarah                   34000
8              9    Heather                   23000
9             10      Holly                   22000